- hosts: all
  become: true
  gather_facts: False
  vars:
    - packages: ["git", "nmap"]
  tasks:
    - name: Installing {{ packages }} on all
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
